 export const menus =[

    {
     menu_aid: 1,
     menu_title: "2pc Chickenjoy",
     menu_category: "Chickenjoy",
     menu_price: "200",
     menu_img:"chicken-1.webp",
     menu_is_active:true ,
    }, 
   
    {
     menu_aid: 2,
     menu_title: "3pc Chickenjoy",
     menu_category: "Chickenjoy",
     menu_price: "280",
     menu_img:"chicken-2.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 3,
     menu_title: "Chickenjoy Bucket meal 2 fries",
     menu_category: "Chickenjoy",
     menu_price: "300",
     menu_img:"chicken-3.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 4,
     menu_title: "Chickenjoy Bucket 1 spaghetti 3 peach mango",
     menu_category: "Chickenjoy",
     menu_price: "350",
     menu_img:"chicken-4.webp",
     menu_is_active:true ,
    }, 
   
    {
     menu_aid: 5,
     menu_title: "Chickenjoy 1 fries ",
     menu_category: "Chickenjoy",
     menu_price: "250",
     menu_img:"chicken-5.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 6,
     menu_title: "Chickenjoy Bucket 1",
     menu_category: "Chickenjoy",
     menu_price: "320",
     menu_img:"chicken-6.webp",
     menu_is_active:true ,
    }, 
   
    {
     menu_aid: 7,
     menu_title: "Peach Mango",
     menu_category: "Dessert",
     menu_price: "60",
     menu_img:"dessert-1.webp",
     menu_is_active: false ,
    }, 
    {
     menu_aid: 8,
     menu_title: "Peach Ube",
     menu_category: "Dessert",
     menu_price: "60",
     menu_img:"dessert-2.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 9,
     menu_title: "Peach Mango 5 pieces",
     menu_category: "Dessert",
     menu_price: "230",
     menu_img:"dessert-3.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 10,
     menu_title: "Pineapple Juice",
     menu_category: "Dessert",
     menu_price: "50",
     menu_img:"dessert-4.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 11,
     menu_title: "Pepsi",
     menu_category: "Dessert",
     menu_price: "50",
     menu_img:"dessert-5.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 12,
     menu_title: "Regular Burger ",
     menu_category: "Burger",
     menu_price: "40",
     menu_img:"burger-1.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 13,
     menu_title: "Cheese Burger",
     menu_category: "Burger",
     menu_price: "60",
     menu_img:"burger-2.webp",
     menu_is_active:true ,
    }, 
   
    {
     menu_aid: 14,
     menu_title: "Palabok",
     menu_category: "Palabok",
     menu_price: "100",
     menu_img:"palabok-1.webp",
     menu_is_active:true,
    }, 
    {
     menu_aid: 15,
     menu_title: "Palabok with coke",
     menu_category: "Palabok",
     menu_price: "120",
     menu_img:"palabok-2.webp",
     menu_is_active:true,
    }, 
    {
     menu_aid: 16,
     menu_title: "Fries",
     menu_category: "Sides",
     menu_price: "40",
     menu_img:"sides-1.webp",
     menu_is_active:true ,   
     }, 
    {
     menu_aid: 17,
     menu_title: "Mash Potato",
     menu_category: "Sides",
     menu_price: "30",
     menu_img:"sides-2.webp",
     menu_is_active:true ,   
     }, 
    {
     menu_aid: 18,
     menu_title: "1 Chicken combo meal",
     menu_category: "Value meal",
     menu_price: "250",
     menu_img:"value-meal-1.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 19,
     menu_title: " 4 Chicken Burger",
     menu_category: "Value meal",
     menu_price: "30",
     menu_img:"value-meal-1.webp",
     menu_is_active:true,
    }, 
    {
     menu_aid: 20,
     menu_title: " 1 Spaghetti",
     menu_category: "Spaghetti",
     menu_price: "80",
     menu_img:"spag-1.webp",
     menu_is_active:true ,   
    }, 
    {
     menu_aid: 21,
     menu_title: " 1 Spaghetti with  1 chicken",
     menu_category: "Spaghetti",
     menu_price: "120",
     menu_img:"spag-2.webp",
     menu_is_active:true ,  
     }, 
    {
     menu_aid: 22,
     menu_title: " 3 Burger Steak",
     menu_category: "BurgerSteak",
     menu_price: "120",
     menu_img:"steak-1.webp",
     menu_is_active:true ,  
      }, 
    {
     menu_aid: 22,
     menu_title: " Bucket Burger Steak",
     menu_category: "BurgerSteak",
     menu_price: "50",
     menu_img:"steak-2.webp",
     menu_is_active:true ,  
      }, 
    {
     menu_aid: 23,
     menu_title: " Bucket Palabok",
     menu_category: "Palabok",
     menu_price: "400",
     menu_img:"steak-3.webp",
     menu_is_active:true ,  
      }, 
    {
     menu_aid: 24,
     menu_title: " Palabok combo meal",
     menu_category: "Palabok",
     menu_price: "700",
     menu_img:"palabok-4.webp",
     menu_is_active:true,
    }, 
    {
     menu_aid: 24,
     menu_title: "Rice",
     menu_category: "Sides",
     menu_price: "30",
     menu_img:"sides-3.webp",
     menu_is_active:true ,   
     }, 
    {
     menu_aid: 25,
     menu_title: "Adobo Rice",
     menu_category: "Sides",
     menu_price: "40",
     menu_img:"sides-4.webp",
     menu_is_active:true ,    
    }, 
  
    {
     menu_aid: 26,
     menu_title: "Spaghetti Bowl",
     menu_category: "Sides",
     menu_price: "40",
     menu_img:"sides-5.webp",
     menu_is_active:true ,    
    }, 
    {
     menu_aid: 27,
     menu_title: "Spaghetti Bucket",
     menu_category: "Spaghetti",
     menu_price: "150",
     menu_img:"spag-3.webp",
     menu_is_active:true ,  
     },
    {
     menu_aid: 28,
     menu_title: "BurgerSteak combo meal",
     menu_category: "BurgerSteak",
     menu_price: "150",
     menu_img:"steak-3.webp",
     menu_is_active:true,
    },
    {
     menu_aid: 29,
     menu_title: "2 Chickenjoy Combo",
     menu_category: "Value meal",
     menu_price: "300",
     menu_img:"value-meal-3.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 30,
     menu_title: "Bucket meal Combo",
     menu_category: "Value meal",
     menu_price: "320",
     menu_img:"value-meal-4.webp",
     menu_is_active:true,
    }, 
    {
     menu_aid: 31,
     menu_title: "Chicken Burger Combo",
     menu_category: "Value meal",
     menu_price: "340",
     menu_img:"value-meal-5.webp",
     menu_is_active:true,
    }, 
  
    {
     menu_aid: 32,
     menu_title: "Burger with fries",
     menu_category: "Burger",
     menu_price: "100",
     menu_img:"burger-2.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 33,
     menu_title: "Cheese burger with fries",
     menu_category: "Burger",
     menu_price: "120",
     menu_img:"burger-4.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 34,
     menu_title: "Big Burger",
     menu_category: "Burger",
     menu_price: "150",
     menu_img:"burger-5.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 35,
     menu_title: "Big Burger Combo",
     menu_category: "Burger",
     menu_price: "170",
     menu_img:"burger-6.webp",
     menu_is_active:true ,
    }, 
    {
     menu_aid: 35,
     menu_title: "Super Burger",
     menu_category: "Burger",
     menu_price: "160",
     menu_img:"burger-6.webp",
     menu_is_active: true ,
    }, 
  
    {
     menu_aid: 36,
     menu_title: "Super Burger with Fries",
     menu_category: "Burger",
     menu_price: "180",
     menu_img:"burger-7.webp",
     menu_is_active: true ,
    }, 
  
]